language: cpp

git:
  submodules: false

matrix:
  include:

    # Linux gcc-4.9
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - doxygen
            - libboost-all-dev
            - libhts-dev
      env:
        - E="CC=gcc-4.9 && CXX=g++-4.9"

    # Linux gcc-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - doxygen
            - libboost-all-dev
            - libhts-dev
      env:
        - E="CC=gcc-5 && CXX=g++-5"

    # Linux gcc-6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - doxygen
            - libboost-all-dev
            - libhts-dev
      env:
        - E="CC=gcc-6 && CXX=g++-6"

    # Linux gcc-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - doxygen
            - libboost-all-dev
            - libhts-dev
      env:
        - E="CC=gcc-7 && CXX=g++-7"

    # OSX gcc-4.9
    - os: osx
      osx_image: xcode8
      addons:
        homebrew:
          packages:
            - htslib
          update: true
      env:
        - E="CC=gcc-4.9 && CXX=g++-4.9"

    # OSX gcc-5
    - os: osx
      osx_image: xcode8
      addons:
        homebrew:
          packages:
            - htslib
          update: true
      env:
        - E="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    # OSX gcc-6
    - os: osx
      osx_image: xcode8
      before_install:
        brew update
      env:
        - E="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    # OSX gcc-7
    - os: osx
      osx_image: xcode8
      before_install:
        brew update
      env:
        - E="brew install gcc && CC=gcc-7 && CXX=g++-7"

    # OSX clang
    - os: osx
      osx_image: xcode9
      before_install:
        brew update
      compiler: clang

    # OSX clang
    - os: osx
      osx_image: xcode8
      before_install:
        brew update
      compiler: clang

    # OSX clang
    - os: osx
      osx_image: xcode7.3
      before_install:
        brew update
      compiler: clang


before_install:
    - eval "${E}"

script:
  mkdir build && cd build && cmake ../src && make

